# Generated by Django 4.1.3 on 2022-11-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0002_remove_pelicula_planeta'),
        ('planeta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeta',
            name='pelicula',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='planetalista', to='pelicula.pelicula'),
            preserve_default=False,
        ),
    ]
