# Generated by Django 4.1.3 on 2022-11-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personaje', '0002_alter_personaje_full_name'),
        ('pelicula', '0002_remove_pelicula_planeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='personaje',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='peliculaslistas', to='personaje.personaje'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PeliculaPersonaje',
        ),
    ]
